# EasyPanel Configuration for Nasiya365
# Domain: my.nasiya365.uz

name: nasiya365

services:
  # MariaDB Database
  mariadb:
    type: mariadb
    image: mariadb:10.6
    rootPassword: ${MARIADB_ROOT_PASSWORD}
    
  # Redis Cache
  redis-cache:
    type: redis
    image: redis:alpine

  # Redis Queue  
  redis-queue:
    type: redis
    image: redis:alpine

  # Main Frappe Backend
  backend:
    type: app
    source:
      type: github
      owner: alraqam
      repo: nasiya365-frappe
    build:
      type: dockerfile
      file: Dockerfile
    deploy:
      command: sh -c "cd sites && ../env/bin/gunicorn -b 0.0.0.0:8000 -w 4 -t 120 frappe.app:application --preload"
    env:
      FRAPPE_SITE_NAME_HEADER: my.nasiya365.uz
      DB_HOST: mariadb
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
    mounts:
      - type: volume
        name: sites
        mountPath: /home/frappe/frappe-bench/sites
      - type: volume
        name: logs
        mountPath: /home/frappe/frappe-bench/logs

  # Nginx Frontend
  frontend:
    type: app
    image: frappe/erpnext:v16
    deploy:
      command: nginx-entrypoint.sh
    domains:
      - host: my.nasiya365.uz
        https: true
    ports:
      - published: 443
        target: 8080
    env:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: my.nasiya365.uz
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      CLIENT_MAX_BODY_SIZE: 50m
    mounts:
      - type: volume
        name: sites
        mountPath: /home/frappe/frappe-bench/sites
      - type: volume
        name: logs
        mountPath: /home/frappe/frappe-bench/logs

  # WebSocket
  websocket:
    type: app
    image: frappe/erpnext:v16
    deploy:
      command: node /home/frappe/frappe-bench/apps/frappe/socketio.js
    env:
      FRAPPE_SITE_NAME_HEADER: my.nasiya365.uz
    mounts:
      - type: volume
        name: sites
        mountPath: /home/frappe/frappe-bench/sites

  # Worker Default Queue
  worker-default:
    type: app
    source:
      type: github
      owner: alraqam
      repo: nasiya365-frappe
    build:
      type: dockerfile
      file: Dockerfile
    deploy:
      command: bench worker --queue default
    mounts:
      - type: volume
        name: sites
        mountPath: /home/frappe/frappe-bench/sites

  # Scheduler
  scheduler:
    type: app
    source:
      type: github
      owner: alraqam
      repo: nasiya365-frappe
    build:
      type: dockerfile
      file: Dockerfile
    deploy:
      command: bench schedule
    mounts:
      - type: volume
        name: sites
        mountPath: /home/frappe/frappe-bench/sites

volumes:
  sites:
  logs:
